runtime: python38

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
#- url: /games/tilebag/static
#  static_dir: clientweb/static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
   
# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -c gunicorn.conf.py server:app

runtime_config:
  python_version: 3

